/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.botframework.connector;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for ActivityType.
 */
public enum ActivityType {
    /** Enum value message. */
    MESSAGE("message"),

    /** Enum value conversationUpdate. */
    CONVERSATION_UPDATE("conversationUpdate"),

    /** Enum value contactRelationUpdate. */
    CONTACT_RELATION_UPDATE("contactRelationUpdate"),

    /** Enum value typing. */
    TYPING("typing"),

    /** Enum value endOfConversation. */
    END_OF_CONVERSATION("endOfConversation"),

    /** Enum value event. */
    EVENT("event"),

    /** Enum value invoke. */
    INVOKE("invoke");

    /** The actual serialized value for a ActivityType instance. */
    private String value;

    ActivityType(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a ActivityType instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed ActivityType object, or null if unable to parse.
     */
    @JsonCreator
    public static ActivityType fromString(String value) {
        ActivityType[] items = ActivityType.values();
        for (ActivityType item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
