/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.botframework.connector;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for CardContentType.
 */
public final class CardContentType extends ExpandableStringEnum<CardContentType> {
    /** Static value application/vnd.microsoft.card.keyboard for CardContentType. */
    public static final CardContentType KEYBOARD = fromString("application/vnd.microsoft.card.keyboard");

    /** Static value application/vnd.microsoft.card.thumbnail for CardContentType. */
    public static final CardContentType THUMBNAIL = fromString("application/vnd.microsoft.card.thumbnail");

    /** Static value application/vnd.microsoft.card.hero for CardContentType. */
    public static final CardContentType HERO = fromString("application/vnd.microsoft.card.hero");

    /** Static value application/vnd.microsoft.card.receipt for CardContentType. */
    public static final CardContentType RECEIPT = fromString("application/vnd.microsoft.card.receipt");

    /** Static value application/vnd.microsoft.card.signin for CardContentType. */
    public static final CardContentType SIGN_IN = fromString("application/vnd.microsoft.card.signin");

    /** Static value application/vnd.microsoft.card.animation for CardContentType. */
    public static final CardContentType ANIMATION = fromString("application/vnd.microsoft.card.animation");

    /** Static value application/vnd.microsoft.card.audio for CardContentType. */
    public static final CardContentType AUDIO = fromString("application/vnd.microsoft.card.audio");

    /** Static value application/vnd.microsoft.card.video for CardContentType. */
    public static final CardContentType VIDEO = fromString("application/vnd.microsoft.card.video");

    /** Static value application/vnd.microsoft.card.payment for CardContentType. */
    public static final CardContentType PAYMENT = fromString("application/vnd.microsoft.card.payment");

    /**
     * Creates or finds a CardContentType from its string representation.
     * @param name a name to look for
     * @return the corresponding CardContentType
     */
    @JsonCreator
    public static CardContentType fromString(String name) {
        return fromString(name, CardContentType.class);
    }

    /**
     * @return known CardContentType values
     */
    public static Collection<CardContentType> values() {
        return values(CardContentType.class);
    }
}
