/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.botframework.connector;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for CardContentType.
 */
public enum CardContentType {
    /** Enum value application/vnd.microsoft.card.keyboard. */
    KEYBOARD("application/vnd.microsoft.card.keyboard"),

    /** Enum value application/vnd.microsoft.card.thumbnail. */
    THUMBNAIL("application/vnd.microsoft.card.thumbnail"),

    /** Enum value application/vnd.microsoft.card.hero. */
    HERO("application/vnd.microsoft.card.hero"),

    /** Enum value application/vnd.microsoft.card.receipt. */
    RECEIPT("application/vnd.microsoft.card.receipt"),

    /** Enum value application/vnd.microsoft.card.signin. */
    SIGN_IN("application/vnd.microsoft.card.signin"),

    /** Enum value application/vnd.microsoft.card.animation. */
    ANIMATION("application/vnd.microsoft.card.animation"),

    /** Enum value application/vnd.microsoft.card.audio. */
    AUDIO("application/vnd.microsoft.card.audio"),

    /** Enum value application/vnd.microsoft.card.video. */
    VIDEO("application/vnd.microsoft.card.video"),

    /** Enum value application/vnd.microsoft.card.payment. */
    PAYMENT("application/vnd.microsoft.card.payment");

    /** The actual serialized value for a CardContentType instance. */
    private String value;

    CardContentType(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a CardContentType instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed CardContentType object, or null if unable to parse.
     */
    @JsonCreator
    public static CardContentType fromString(String value) {
        CardContentType[] items = CardContentType.values();
        for (CardContentType item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
