/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.botframework.connector;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Channel account information for a conversation.
 */
public class ConversationAccount {
    /**
     * Is this a reference to a group.
     */
    @JsonProperty(value = "isGroup")
    private Boolean isGroup;

    /**
     * The ID that identifies the conversation. The ID is unique per channel.
     * If the channel starts the conversion, it sets this ID; otherwise, the
     * bot sets this property to the ID that it gets back in the response when
     * it starts the conversation (Example: joe@smith.com, or @joesmith or
     * 123456).
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * A display name that can be used to identify the conversation.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Get the isGroup value.
     *
     * @return the isGroup value
     */
    public Boolean isGroup() {
        return this.isGroup;
    }

    /**
     * Set the isGroup value.
     *
     * @param isGroup the isGroup value to set
     * @return the ConversationAccount object itself.
     */
    public ConversationAccount withIsGroup(Boolean isGroup) {
        this.isGroup = isGroup;
        return this;
    }

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the ConversationAccount object itself.
     */
    public ConversationAccount withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the ConversationAccount object itself.
     */
    public ConversationAccount withName(String name) {
        this.name = name;
        return this;
    }

}
