/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.botframework.connector;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for ErrorCode.
 */
public final class ErrorCode extends ExpandableStringEnum<ErrorCode> {
    /** Static value 400 for ErrorCode. */
    public static final ErrorCode FOUR_ZERO_ZERO = fromString("400");

    /** Static value 401 for ErrorCode. */
    public static final ErrorCode FOUR_ZERO_ONE = fromString("401");

    /** Static value 403 for ErrorCode. */
    public static final ErrorCode FOUR_ZERO_THREE = fromString("403");

    /** Static value 404 for ErrorCode. */
    public static final ErrorCode FOUR_ZERO_FOUR = fromString("404");

    /** Static value 405 for ErrorCode. */
    public static final ErrorCode FOUR_ZERO_FIVE = fromString("405");

    /** Static value 429 for ErrorCode. */
    public static final ErrorCode FOUR_TWO_NINE = fromString("429");

    /** Static value 500 for ErrorCode. */
    public static final ErrorCode FIVE_ZERO_ZERO = fromString("500");

    /** Static value 503 for ErrorCode. */
    public static final ErrorCode FIVE_ZERO_THREE = fromString("503");

    /**
     * Creates or finds a ErrorCode from its string representation.
     * @param name a name to look for
     * @return the corresponding ErrorCode
     */
    @JsonCreator
    public static ErrorCode fromString(String name) {
        return fromString(name, ErrorCode.class);
    }

    /**
     * @return known ErrorCode values
     */
    public static Collection<ErrorCode> values() {
        return values(ErrorCode.class);
    }
}
