/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.botframework.connector;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for InputHint.
 */
public enum InputHint {
    /** Enum value acceptingInput. */
    ACCEPTING_INPUT("acceptingInput"),

    /** Enum value expectingInput. */
    EXPECTING_INPUT("expectingInput"),

    /** Enum value ignoringInput. */
    IGNORING_INPUT("ignoringInput");

    /** The actual serialized value for a InputHint instance. */
    private String value;

    InputHint(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a InputHint instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed InputHint object, or null if unable to parse.
     */
    @JsonCreator
    public static InputHint fromString(String value) {
        InputHint[] items = InputHint.values();
        for (InputHint item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
