/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.botframework.connector;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Object describing a media thumbnail.
 */
public class ThumbnailUrl {
    /**
     * URL pointing to an thumbnail to use for media content.
     */
    @JsonProperty(value = "url")
    private String url;

    /**
     * Alt text to display for screen readers on the thumbnail image.
     */
    @JsonProperty(value = "alt")
    private String alt;

    /**
     * Get the url value.
     *
     * @return the url value
     */
    public String url() {
        return this.url;
    }

    /**
     * Set the url value.
     *
     * @param url the url value to set
     * @return the ThumbnailUrl object itself.
     */
    public ThumbnailUrl withUrl(String url) {
        this.url = url;
        return this;
    }

    /**
     * Get the alt value.
     *
     * @return the alt value
     */
    public String alt() {
        return this.alt;
    }

    /**
     * Set the alt value.
     *
     * @param alt the alt value to set
     * @return the ThumbnailUrl object itself.
     */
    public ThumbnailUrl withAlt(String alt) {
        this.alt = alt;
        return this;
    }

}
