/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.botframework.connector.implementation;

import com.microsoft.azure.botframework.connector.Error;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An HTTP API response.
 */
public class ErrorResponseInner {
    /**
     * Error message.
     */
    @JsonProperty(value = "error")
    private Error error;

    /**
     * Get the error value.
     *
     * @return the error value
     */
    public Error error() {
        return this.error;
    }

    /**
     * Set the error value.
     *
     * @param error the error value to set
     * @return the ErrorResponseInner object itself.
     */
    public ErrorResponseInner withError(Error error) {
        this.error = error;
        return this;
    }

}
